name: Run Toto Tracker

on:
  workflow_dispatch: # 依然保留手动触发按钮
  schedule:
    # 转换为 UTC 时间：马本地时间晚 20:30 (UTC 12:30)
    # 每周三、周六、周日自动执行
    - cron: '30 12 * * 3,6,0'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        run: python main.py
